#!/bin/bash

# Variable declaration
branch=$(git rev-parse --abbrev-ref HEAD) # Command to get current git branch
classpath=../lib/*:.
test_levels='../levels/performance_test_levels'
dateNow=$(date +"%c")
result_file_name=test_results.txt

# Change class path if on Windows
if [[ "$OSTYPE" == "msys" ]]; then
	classpath="../lib/*;./"
fi

# Cleaning project
rm -rf out

# Compiling project
cd src
javac -cp $classpath Main.java -d ../out > /dev/null 2>&1
cd ../out

# Test result headline (current branch, date and time)
if [[ $1 != "" ]]; then
    echo $1 >> ../$result_file_name
    echo  "User: $(whoami), Branch: $branch, $dateNow" >> ../$result_file_name
fi

# Write test results for each lvl 
for lvl in "$test_levels"/*.lvl
do
  # Pass lvl data to AI program, 
  # filter its output to lines with word "Found"
  # and write each line to terminal and file "test_results" 
  cat $lvl |  java -cp $classpath Main &>  >(grep "Found") >&2  | 
  {
      # Read line and print to both file and terminal
      read i 
      if [[ $1 != "" ]]; then
         echo "$(basename $lvl): $i" >>  ../$result_file_name
         echo "Successfully stored results for level $(basename $lvl) in test_results.txt"
      else 
         echo "$(basename $lvl): $i"
      fi
  }
done

# New line to end test result section in file
if [[ $1 != "" ]]; then
  printf "\n" >> ../$result_file_name  
fi
